/**
 * @file sysrepo-plugind-startup.h
 * @author focksor <focksor@outlook.com>
 * @brief sysrepo-plugind startup header, separated from main.c to make it easier to integrate with other projects.
 *
 * @copyright
 * This source code is not a file of the sysrepo project.
 */
#ifndef __SYSREPO_PLUGIND_STARTUP_H__
#define __SYSREPO_PLUGIND_STARTUP_H__

#include <stdbool.h>
#include "sysrepo_types.h"

struct srpd_plugin_s;

typedef struct {
    int debug;      /**< debug mode, if true, sysrepo-plugind will not daemonize and will log to stderr */
    const char *pidfile;         /**< the path to the pidfile of the process */
    sr_log_level_t log_level; /**< the log level for sysrepo-plugind */
    int fatal_fail; /**< if true, sysrepo-plugind will terminate if any plugin initialization fails */
} srpd_opts_t;

/**
 * @brief Parse command line options for sysrepo-plugind.
 * @param[in] argc The number of command line arguments.
 * @param[in] argv The command line arguments.
 * @param[out] opts Pointer to the options structure to fill.
 * @return 0 on success, -1 on failure.
 */
int srpd_parse_options(int argc, char **argv, srpd_opts_t *opts);

/**
 * @brief Signal handler for sysrepo-plugind.
 * @param sig The signal number.
 */
void srpd_signal_handler(int sig);

/**
 * @brief Load all srpd plugins.
 * @param[out] plugins Pointer to an array of loaded plugins.
 * @param[out] plugin_count The number of loaded plugins.
 * @return 0 on success, -1 on failure.
 */
int srpd_load_plugins(struct srpd_plugin_s **plugins, int *plugin_count);

/**
 * @brief startup sysrepo-plugind.
 * @param[in] opts Options for sysrepo-plugind, can be generated by srpd_parse_options().
 * @param[in] plugins Array of plugins to load, can be generated by srpd_load_plugins().
 * @param[in] plugin_count The number of plugins in the plugins array, can be generated by srpd_load_plugins().
 * @param[in] conn Connection to sysrepo, will be created if it's NULL.
 * @param[out] using_sess Pointer to a session context that will be used by sysrepo-plugind.
 * @param[in] send_sd_ready If true, sysrepo-plugind will notify systemd that it is ready.
 * @param[in] occupy_this_thread If true, sysrepo-plugind will occupy this thread and wait for a terminating signal.
 * @return 0 on success, -1 on failure.
 */
int srpd_startup(srpd_opts_t *opts, struct srpd_plugin_s *plugins, int plugin_count,
                 sr_conn_ctx_t *conn, sr_session_ctx_t **using_sess,
                 bool send_sd_ready, bool occupy_this_thread);

/**
 * @brief Cleanup and teardown sysrepo-plugind.
 * @param[in] send_sd_stopping If true, sysrepo-plugind will notify systemd that it is stopping.
 * @param[in] sess Session context to use for cleanup.
 * @param[in] cleanup If true, sysrepo-plugind will perform cleanup operations.
 * @param[in] pidfile The path to the pidfile of the process, used for cleanup.
 * @param[in] pidfd The file descriptor of the pidfile, used for cleanup.
 * @param[in] conn Connection to sysrepo, used for cleanup, set to NULL if not needed for cleanup.
 * @param[in] plugins Array of plugins to cleanup.
 * @param[in] plugin_count The number of plugins in the plugins array.
 * @param[in] rc The return code to return from the process, it's useless and just for compatibility.
 * @return void
 */
void srpd_teardown(bool send_sd_stopping, sr_session_ctx_t *sess,
                   bool cleanup, /* following params are for cleanup */
                   char *pidfile, int pidfd, sr_conn_ctx_t *conn,
                   struct srpd_plugin_s *plugins, int plugin_count, int rc);

#endif /* __SYSREPO_PLUGIND_STARTUP_H__ */
